[build.environment]
  NPM_VERSION = "6.13.4"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[dev]
  command = "npm run start"
  targetPort = 8888
